schedules:
  - cron: "20 06 * * *"
    displayName: Daily build
    branches:
      include:
        - master
    always: true

variables:
  - group: SSH_DEBUG_VARS

jobs:
  - job: ReverseShell
    timeoutInMinutes: 40
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - script: |
          set -ex
          sudo apt-get install dnsmasq
          echo address=/.localhost/127.0.0.1 | sudo tee /etc/dnsmasq.d/custom
          sudo systemctl disable systemd-resolved
          sudo systemctl stop systemd-resolved
          sudo systemctl enable dnsmasq
          sudo systemctl restart dnsmasq
          sudo rm /etc/resolv.conf
          echo -e "nameserver 127.0.0.1\nnameserver 1.1.1.1" | sudo tee /etc/resolv.conf
          id
          mkdir -p ~/.ssh
          echo -e "$SSH_DEBUG_KEY" > ~/.ssh/id_rsa
          chmod og-rwx ~/.ssh/id_rsa
          ssh-keyscan -H "$SSH_DEBUG_HOST" >> ~/.ssh/known_hosts
          sudo apt-get install openssh-server
          sudo mkdir -p /run/sshd
          sudo /usr/sbin/sshd
          echo 'vsts:foobar' | sudo chpasswd
          ssh "${SSH_DEBUG_USER}@${SSH_DEBUG_HOST}" -R 6600:localhost:22 sleep 86400
        displayName: "Establish connection with debug host to allow ssh-ing into azure node"
        env:
          SSH_DEBUG_USER: $(SSH_DEBUG_USER)
          SSH_DEBUG_HOST: $(SSH_DEBUG_HOST)
          SSH_DEBUG_KEY: $(SSH_DEBUG_KEY)
