schedules:
  - cron: "30 06 * * *"
    displayName: Daily build
    branches:
      include:
        - master
    always: true

jobs:
  - job: TestMinimal
    timeoutInMinutes: 40
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - template: azure-pipelines/setup.yml

      - script: |
          set -ex
          cd tests/fixtures/minimal/
          derex reset-mysql
          derex ecommerce reset-mysql
          derex reset-rabbitmq
        displayName: "Prime Mysql and Rabbitmq"

      - script: |
          set -ex
          cd tests/fixtures/minimal/
          derex runmode production
          ddc-project config
          ddc-project up -d lms ecommerce ecommerce_worker
        displayName: "Start lms and ecommerce"

      - script: |
          set -ex
          cd tests/fixtures/minimal/
          ddc-project logs
        displayName: "Show logs"

      - script: |
          set -ex
          CMD="curl --connect-timeout 30 --retry 5 --retry-delay 5 -f http://localhost:4900/health/"
          $CMD || (sleep 10; $CMD )
        displayName: "Curl the ecommerce"

  - job: TestComplete
    timeoutInMinutes: 40
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - template: azure-pipelines/setup.yml

      - script: |
          set -ex
          cd tests/fixtures/complete/
          derex reset-mysql
          derex ecommerce reset-mysql
          derex reset-rabbitmq
        displayName: "Prime Mysql and Rabbitmq"

      - script: |
          set -ex
          cd tests/fixtures/complete/
          derex runmode production
          ddc-project config
          ddc-project up -d lms ecommerce ecommerce_worker
        displayName: "Start lms and ecommerce"

      - script: |
          set -ex
          cd tests/fixtures/complete/
          ddc-project logs
        displayName: "Show logs"

      - script: |
          set -ex
          CMD="curl --connect-timeout 30 --retry 5 --retry-delay 5 -f http://localhost:4900/health/"
          $CMD || (sleep 10; $CMD )
        displayName: "Curl the ecommerce"
