schedules:
  - cron: "20 06 * * *"
    displayName: Daily build
    branches:
      include:
        - master
    always: true

jobs:
  - template: azure-pipelines/minimal.yml
    parameters:
      JOB_VARIANT: UnPinned

  - template: azure-pipelines/minimal.yml
    parameters:
      JOB_VARIANT: Pinned

  - template: azure-pipelines/complete.yml
    parameters:
      JOB_VARIANT: UnPinned

  - template: azure-pipelines/complete.yml
    parameters:
      JOB_VARIANT: Pinned

variables:
  - name: UBUNTU_VERSION
    value: ubuntu-latest
