schedules:
  - cron: "30 06 * * *"
    displayName: Daily build
    branches:
      include:
        - master
    always: true

jobs:
  - job: SetupAndTest
    timeoutInMinutes: 40
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.7"
        displayName: "Use Python 3.7"

      - script: |
          pip3 install -U pip setuptools
          pip3 install -r requirements.txt . git+https://github.com/Abstract-Tech/pytest-azurepipelines.git
        displayName: "Install dependencies"

      - script: ddc-services up -d
        displayName: "Start services"

      - script: |
          set -ex
          cd tests/fixtures/minimal/
          derex reset-mysql
          derex reset-rabbitmq
        displayName: "Prime Mysql, Rabbitmq and Elasticsearch"

      - script: |
          set -ex
          cd tests/fixtures/minimal/
          ddc-project config
          ddc-project up -d lms ecommerce ecommerce_worker
        displayName: "Start lms and ecommerce"

      - script: |
          set -ex
          cd tests/fixtures/minimal/
          ddc-project logs
        displayName: "Show logs"
