project_name: ecommerce-complete
openedx_version: ironwood
plugins:
  derex.ecommerce: {}

variables:
  LMS_JWT_ISSUER:
    base: http://complete.localhost/oauth2
  LMS_JWT_AUDIENCE:
    base: lms-key
  LMS_JWT_SECRET_KEY:
    base: lms-secret

  CMS_JWT_ISSUER:
    base: http://complete.localhost/oauth2
  CMS_JWT_AUDIENCE:
    base: lms-key
  CMS_JWT_SECRET_KEY:
    base: lms-secret

  ECOMMERCE_JWT_ISSUER:
    base: http://complete.localhost/oauth2
  ECOMMERCE_JWT_AUDIENCE:
    base: lms-key
  ECOMMERCE_JWT_SECRET_KEY:
    base: lms-secret
