# DO NOT EDIT THIS FILE!
# IT CAN BE OVERWRITTEN ON UPGRADE.
# Generated by derex.runner 0.3.3

import os


DATABASES = {
    "default": {
        "ATOMIC_REQUESTS": True,
        "ENGINE": "django.db.backends.mysql",
        "HOST": "mysql",
        "NAME": os.environ["MYSQL_DB_NAME"],
        "USER": os.environ["MYSQL_USER"],
        "PASSWORD": os.environ["MYSQL_PASSWORD"],
        "PORT": "3306",
    }
}
