parameters:
  - name: JOB_VARIANT
    type: string

jobs:
  - job: Complete${{ parameters.JOB_VARIANT }}
    timeoutInMinutes: 40
    pool:
      vmImage: $(UBUNTU_VERSION)
    steps:
      - template: setup.yml
        parameters:
          JOB_VARIANT: ${{ parameters.JOB_VARIANT }}

      - script: |
          set -ex
          cd examples/ironwood/complete/
          derex mysql reset --force
          derex ecommerce reset-mysql
          derex ecommerce load-fixtures
        displayName: "Prime Mysql"

      - script: |
          set -ex
          cd examples/ironwood/complete/
          derex runmode production
          ddc-project config
          ddc-project up -d lms ecommerce ecommerce_worker
        displayName: "Start lms and ecommerce"

      - script: |
          set -ex
          cd examples/ironwood/complete/
          ddc-project logs
        displayName: "Show logs"

      - script: |
          set -ex
          curl -sf http://ecommerce.ecommerce-complete.localhost/health/ \
            --connect-timeout 30 \
            --retry 5 \
            --retry-delay 5 \
            --retry-connrefused ||
          curl http://ecommerce.ecommerce-complete.localhost/health/
        displayName: "Curl the Ecommerce service"
